# Generated by Django 4.2 on 2023-04-17 11:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EventAPP', '0002_alter_participants_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='participants',
            options={'default_related_name': 'participants'},
        ),
    ]
